version: 2

project_name: "webstack-go"

builds:
  - id: default
    dir: .  # 根目录
    main: ./cmd/server  # 指定 main 包的路径
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: "config/*"
        dst: "config"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^feat:"
    - title: "Bug Fixes"
      regexp: "^fix:"
    - title: "Performance Improvements"
      regexp: "^perf:"
    - title: "Other Changes"
      regexp: "^.*$"

release:
  draft: false
  prerelease: false
  mode: replace
  footer: |
    ## Contributors

    Thank you to all the contributors who helped make this release possible!

    {{ range .Contributors }}
    - [{{ .Login }}]({{ .HTMLURL }})
    {{ end }}

  header: |
    # {{ .ProjectName }} {{ .Version }}

    **Release Date:** {{ .Date }}

    ## What's Changed

    {{ if .Changelog }}
    {{ .Changelog }}
    {{ else }}
    No significant changes in this release.
    {{ end }}

    ## Installation

    Download the pre-built binaries for your platform:

    ```bash
    # Linux (amd64)
    curl -L -o webstack-go.tar.gz https://github.com/{{ .Repo.Owner }}/{{ .Repo.Name }}/releases/download/v{{ .Version }}/webstack-go_{{ .Version }}_linux_amd64.tar.gz

    # macOS (arm64)
    curl -L -o webstack-go.tar.gz https://github.com/{{ .Repo.Owner }}/{{ .Repo.Name }}/releases/download/v{{ .Version }}/webstack-go_{{ .Version }}_darwin_arm64.tar.gz

    # Windows (amd64)
    curl -L -o webstack-go.zip https://github.com/{{ .Repo.Owner }}/{{ .Repo.Name }}/releases/download/v{{ .Version }}/webstack-go_{{ .Version }}_windows_amd64.zip
    ```

    ## Documentation

    For more details, please refer to the [documentation](https://github.com/{{ .Repo.Owner }}/{{ .Repo.Name }}/wiki).

    ## Support

    If you encounter any issues, please [open an issue](https://github.com/{{ .Repo.Owner }}/{{ .Repo.Name }}/issues).

    ---

git:
  ignore_tags:
    - alpha
    - beta